version: '3.8'

services:
  api_services:
    container_name: api_service
    restart: always
    build:
      context: .
    ports:
      - "6767:6767"
    volumes:
      - ./backups:/app/backups
      - ./datasets:/app/datasets
      - ./dataset_models:/app/dataset_models
    environment:
      - BACKUPS_FOLDER=./backups/
      - DATASET_FOLDER=./datasets/
      - DATASET_MODEL_FOLDER=./dataset_models/
    env_file: .env
